In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1


# INTRO TO TENSORS 

A tensor is a mathematical tool that describes how different mathematical objects (like vectors) relate to each other in a linear manner across multiple dimensions. This means tensors can capture complex relationships that simple numbers, vectors, or matrices cannot.
Key Characteristics
Multilinear Relationships
In practical terms, this means a tensor can:
Map between different vector spaces
Represent linear transformations
Describe how quantities change across different directions
Vector Space Context
Tensors are not standalone objects but are fundamentally connected to vector spaces. They describe how quantities transform and interact within these spaces.
Practical Example
Consider electrical conductivity in a crystal. Instead of a simple one-to-one relationship between current and electric field, a tensor allows for more complex interactions:
Current in one direction can depend on electric fields in multiple directions
Each component can be linearly related to other components in a systematic way1
Mathematical Depth
At its most rigorous, a tensor can be defined as a multilinear map that transforms according to specific rules. This means it:
Can represent relationships across multiple dimensions
Maintains consistent transformation properties regardless of coordinate system24
The beauty of tensors is their ability to generalize mathematical concepts from simple scalars to incredibly complex, multi-dimensional representations of physical and mathematical phenomena.


In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#get tensor back as python int
scalar.item()

7

In [5]:
#vector
vector = torch.tensor([3,5])
print(vector.ndim, vector.shape)

1 torch.Size([2])


In [6]:
#matrix
matrix = torch.tensor([[7, 8],
                      [6, 7],
                      [8, 9]])
print(matrix, matrix.ndim, matrix.shape)

tensor([[7, 8],
        [6, 7],
        [8, 9]]) 2 torch.Size([3, 2])


In [7]:
#updating torch to tensor
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
print(tensor, tensor.ndim, tensor.shape) #from shapeinstance, rows, columns

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) 3 torch.Size([1, 3, 3])


## RANDOM TENSORS 

random tensors are used for NN learning, tensors full of random numbers and then adjust it to those random numbers to better representation 

In [8]:
random_tensor = torch.rand(5,6, 10)
print(random_tensor, random_tensor.ndim, random_tensor.size)

tensor([[[0.2100, 0.4592, 0.2641, 0.1679, 0.2456, 0.7115, 0.1912, 0.8633,
          0.5085, 0.7652],
         [0.5859, 0.7707, 0.2019, 0.6470, 0.3251, 0.7310, 0.6694, 0.0686,
          0.0822, 0.9873],
         [0.0943, 0.6505, 0.6217, 0.4992, 0.6844, 0.3609, 0.4589, 0.8007,
          0.7932, 0.2167],
         [0.2161, 0.3289, 0.7565, 0.7380, 0.9762, 0.1973, 0.3521, 0.4174,
          0.9524, 0.4609],
         [0.7195, 0.1889, 0.9984, 0.6196, 0.1302, 0.8796, 0.2148, 0.3943,
          0.9945, 0.6622],
         [0.9174, 0.6021, 0.7064, 0.3960, 0.7503, 0.2939, 0.6467, 0.4794,
          0.3448, 0.0812]],

        [[0.7314, 0.4307, 0.2879, 0.1587, 0.2972, 0.7200, 0.8714, 0.5774,
          0.3313, 0.9472],
         [0.9757, 0.0645, 0.4511, 0.6071, 0.9116, 0.2049, 0.5291, 0.6795,
          0.7367, 0.5968],
         [0.7735, 0.0474, 0.3455, 0.0260, 0.9573, 0.6704, 0.2936, 0.3244,
          0.4518, 0.2288],
         [0.8032, 0.0133, 0.1802, 0.0614, 0.5718, 0.0794, 0.6098, 0.7252,
          0.349

In [9]:
#creating a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))#ht, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### TENSOR MANIPULATION 

In [10]:
# zeros and ones
zeros = torch.zeros(size=(5,6,10))
p = zeros*random_tensor
p

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0.,

In [11]:
ones = torch.ones(size=(5,6,10))
ones.dtype

torch.float32

In [12]:
#creating a range of tensors and tensors-like
hope = torch.arange(start=1,end=100,step=39)
hope

tensor([ 1, 40, 79])

In [13]:
#creating tensors like
ten_zeros = torch.zeros_like(input=hope)
ten_zeros

tensor([0, 0, 0])

#### TENSOR DATATYPES

In [14]:
float_32_t = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)
float_32_t

tensor([3., 6., 9.])

In [15]:
float_16_t = float_32_t.type(torch.half)
float_16_t

tensor([3., 6., 9.], dtype=torch.float16)

In [16]:
int_32_t = torch.tensor([3,6,9], dtype = torch.long)
int_32_t

tensor([3, 6, 9])

In [17]:
float_32_t * int_32_t

tensor([ 9., 36., 81.])

In [18]:
s_t = torch.rand(3,4)
s_t

tensor([[0.2831, 0.2654, 0.7318, 0.3904],
        [0.8808, 0.2785, 0.4642, 0.4005],
        [0.3435, 0.0167, 0.9194, 0.9335]])

In [19]:
print(s_t)
print(f'dtype of tensor and shape:{s_t.dtype}, {s_t.shape}, {s_t.size()}')


tensor([[0.2831, 0.2654, 0.7318, 0.3904],
        [0.8808, 0.2785, 0.4642, 0.4005],
        [0.3435, 0.0167, 0.9194, 0.9335]])
dtype of tensor and shape:torch.float32, torch.Size([3, 4]), torch.Size([3, 4])


In [20]:
print(f'device tensor is on :{s_t.device}')

device tensor is on :cpu


In [21]:
#some random tensors
tg = torch.rand((5,5), dtype = torch.float32, requires_grad=True, device = 'cuda').long()
pg = torch.ones((5,5), dtype = torch.float64, requires_grad = True, device='cuda')
cg = tg * pg
print(cg.item)

<built-in method item of Tensor object at 0x0000025C8BE75C20>


In [22]:
import torch 
import torch.nn.functional as F

In [23]:
ip_t = torch.rand([4,4], dtype = torch.float32).unsqueeze(0).unsqueeze(0)
kernel = torch.tensor([
    [0, -1, 0],
    [-1, 5, -1],
    [0, -1, 0]
], dtype=torch.float32).unsqueeze(0).unsqueeze(0)

op = F.conv2d(ip_t, kernel)
print(ip_t)
print('op shape:', op.shape)
print('op', op)
#(1,1,2,2) -> batch size, no of channels, height, width

tensor([[[[0.5058, 0.2337, 0.5131, 0.2154],
          [0.8982, 0.0829, 0.7936, 0.6868],
          [0.3216, 0.4216, 0.8504, 0.1089],
          [0.9809, 0.1522, 0.7866, 0.1378]]]])
op shape: torch.Size([1, 1, 2, 2])
op tensor([[[[-1.9325,  1.8346],
          [ 0.7008,  2.1413]]]])


#### TENSOR OPERATIONS 
all arithmetic and matrix operations

In [24]:
# addition 
tensor = torch.tensor([4,5,6])
p = tensor+100
q = tensor * 100
r = tensor // 5
s = tensor % 4
t = tensor / 10
print(p,q,r,s,t)

tensor([104, 105, 106]) tensor([400, 500, 600]) tensor([0, 1, 1]) tensor([0, 1, 2]) tensor([0.4000, 0.5000, 0.6000])


#### MATRIX MULTIPLICATION 
1. inner dimentions must match
2. resulting matrix has the shape of the outer dimentions 

In [25]:
print(tensor, ' * ', tensor)
print(f'equals: {tensor * tensor}')

tensor([4, 5, 6])  *  tensor([4, 5, 6])
equals: tensor([16, 25, 36])


In [26]:
torch.matmul(tensor, tensor)

tensor(77)

In [27]:
value = 0 
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(77)


In [28]:
torch.matmul(tensor, tensor)

tensor(77)

In [29]:
tensor @ tensor

tensor(77)

In [30]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.1231, 0.1782, 0.0956],
        [0.1456, 0.5733, 0.2948],
        [0.5035, 1.0176, 0.5356]])

#### Most common errors in DL

In [31]:
tensor_a = torch.tensor([[1,2],
                       [3,4],
                       [5,6]])
tensor_b = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.mm(tensor_a, tensor_b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

to fix the above issue, we can use Transpose 

In [32]:
transpose = tensor_b.T

In [33]:
torch.mm(tensor_a, transpose)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [34]:
print(f'original shapes: tensor_a ={tensor_a.shape}, tensor_b = {tensor_b.shape}')
print(f'new shapes: tensor_a = {tensor_a.shape}, tensor_b ={transpose.shape}')
print(f'multiplying: {tensor_a.shape} @ {transpose.shape}')

original shapes: tensor_a =torch.Size([3, 2]), tensor_b = torch.Size([3, 2])
new shapes: tensor_a = torch.Size([3, 2]), tensor_b =torch.Size([2, 3])
multiplying: torch.Size([3, 2]) @ torch.Size([2, 3])


## TENSOR AGGREGATION 
1.MIN
2.MAX
3.SUM , etc

In [35]:
#create a tensor 
x = torch.arange(0, 100, 10)
x.dtype

torch.int64

In [36]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [37]:
torch.max(x), x.max

(tensor(90), <function Tensor.max>)

In [38]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [39]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [40]:
#argmax and argmin, for finding postitional min and max
print(x.argmax(),x.argmin())

tensor(9) tensor(0)


#### RESHAPE. VIEW AND STACK TENSORS, squeezing and un-squeezing 
1. reshaping - reshape an ip tensor to a defined shape
2. view - return a view of an ip tensor of certain shape but keep the same mem as the original tensor
3. stacking - combine multiple tensors on top of each other (vstack) or by side (hstack)
4. squeeze - remove all 1 dim from a tensors
5. unsqueeze - add a 1 dim to a tensor
6. permute - return a view of ip with a dims permuted (swapped) in certain way

In [41]:
import torch
x = torch.arange(1., 10,)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [42]:
# reshape
re_shape = x.reshape(3,3)
re_shape, re_shape.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [43]:
#change the view
z = x.view(1,9)
z, z.shape
#changing z changes the x (original view of a tensor shares the same mem as the original
z[:, 0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [44]:
#stack tensors one on each other
x_stack = torch.stack([x,x,x,x], dim=0)
x_stack

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [45]:
# squeezing and unsqueezing

In [46]:
re_shape.squeeze().squeeze().shape

torch.Size([3, 3])

In [47]:
# torch unsqueeze
re_shape.unsqueeze(dim=0).unsqueeze(dim=1).shape

torch.Size([1, 1, 3, 3])

In [48]:
#premute - rearrange target tensor in specififed order
p = torch.rand(size = (224, 224, 3))
p.size()

torch.Size([224, 224, 3])

In [49]:
l = p.permute(2,0,1)
l.size()

torch.Size([3, 224, 224])

### INDEXING (selecting data from tensors)

In [50]:
import torch
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [51]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [52]:
x[0,0]

tensor([1, 2, 3])

In [53]:
x[0,1]

tensor([4, 5, 6])

In [54]:
x[0,0,1]

tensor(2)

### torch to numpy

In [55]:
import torch 
import numpy as np

In [56]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [57]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float32)

In [58]:
#tensor to numpy array 
tensor = torch.ones(7)
nupy_t = tensor.numpy()
tensor, nupy_t

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### REPRODUCIABILITY trying to take the random out of random
to reduce the randomness in NN, pytorch comesup with --> random seed

In [59]:
import torch
random_te = torch.rand(3,4)
random_ta = torch.rand(3,4)
print(random_ta, random_te)
print(random_te==random_ta)

tensor([[0.0708, 0.6916, 0.1160, 0.1454],
        [0.5728, 0.2570, 0.7093, 0.7959],
        [0.0361, 0.1320, 0.9546, 0.8293]]) tensor([[0.5494, 0.5430, 0.8311, 0.9059],
        [0.3069, 0.9291, 0.6199, 0.6379],
        [0.1086, 0.9584, 0.8488, 0.2406]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [60]:
#random but reproduciable tensors
import torch 
random_seed = 42
torch.manual_seed(random_seed)
random_ta = torch.rand(3,4)
torch.manual_seed(random_seed)
random_te = torch.rand(3,4)

print(random_ta, random_te)
print(random_ta == random_te)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# ACCESSING GGPPUU

In [61]:
! nvidia-smi

Wed Jan 15 21:39:15 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 556.12                 Driver Version: 556.12         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce MX330         WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   64C    P8             N/A / ERR!  |       0MiB /   2048MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [62]:
# checking the GPU access with pytorch
import torch 
torch.cuda.is_available()

True

# setting up device agostic code

In [63]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [64]:
# number of devices
torch.cuda.device_count()

1

In [65]:
# agnositic code
import argparse
import torch 

In [66]:
parser = argparse.ArgumentParser(description='Pytorch')
parser.add_argument('--disable-cuda', action='store_true', help='Disable CUDA')
args = parser.parse_args()
args.device = None
if not args.disable_cuda and torch.cuda.is_available():
    args.device = torch.device('cuda')
else:
    args.device = torch.device('cpu')

usage: ipykernel_launcher.py [-h] [--disable-cuda]
ipykernel_launcher.py: error: unrecognized arguments: -f C:\Users\DELL\AppData\Roaming\jupyter\runtime\kernel-6d08993f-6722-4bfe-a362-384592b54087.json


SystemExit: 2

C:\Users\DELL\anaconda3\envs\pytorch\Lib\site-packages\IPython\core\interactiveshell.py:3585: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [67]:
#create a tensor, default is on GPU
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [68]:
tensor_on_g = tensor.to(device)
tensor_on_g

tensor([1, 2, 3], device='cuda:0')

In [69]:
## moving tensors back to CPU
tensor_on_g.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [70]:
#to fix the above error
tensor_b_cp = tensor_on_g.cpu().numpy()
print(tensor_b_cp,tensor_on_g)

[1 2 3] tensor([1, 2, 3], device='cuda:0')


# EXERCISES WITH SOLUTIONS 

### 2. Create a random tensor of shape (7,7)

In [74]:
import torch 
tensor = torch.rand(7,7)
tensor

tensor([[0.1587, 0.6542, 0.3278, 0.6532, 0.3958, 0.9147, 0.2036],
        [0.2018, 0.2018, 0.9497, 0.6666, 0.9811, 0.0874, 0.0041],
        [0.1088, 0.1637, 0.7025, 0.6790, 0.9155, 0.2418, 0.1591],
        [0.7653, 0.2979, 0.8035, 0.3813, 0.7860, 0.1115, 0.2477],
        [0.6524, 0.6057, 0.3725, 0.7980, 0.8399, 0.1374, 0.2331],
        [0.9578, 0.3313, 0.3227, 0.0162, 0.2137, 0.6249, 0.4340],
        [0.1371, 0.5117, 0.1585, 0.0758, 0.2247, 0.0624, 0.1816]])

### 3.Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [79]:
import torch 
tensor2 = torch.rand(1,7)
tensor_T = tensor2.t()
matrix = torch.matmul(tensor, tensor_T)
print(matrix, tensor2, tensor_T)

tensor([[1.1699],
        [1.6426],
        [1.5418],
        [1.9253],
        [1.8467],
        [1.4598],
        [0.6740]]) tensor([[0.6258, 0.2849, 0.4452, 0.1258, 0.9554, 0.1330, 0.7672]]) tensor([[0.6258],
        [0.2849],
        [0.4452],
        [0.1258],
        [0.9554],
        [0.1330],
        [0.7672]])


### 4. set the random seed to 0 and do 2 & 3 over again

In [87]:
import torch 
torch.manual_seed(3)
torch.cuda.manual_seed(456) #for GPU 5
x = torch.rand(7,7)
y = torch.rand(1,7)
Y_t = y.t()
print(Y_t)

tensor([[0.9623],
        [0.7606],
        [0.2981],
        [0.4291],
        [0.9418],
        [0.8212],
        [0.6247]])


### 6.Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed)

In [89]:
import torch
torch.manual_seed(2345)
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'Device : {device}')
t1 = torch.rand(2,3).to(device)
t2 = torch.rand(2,3).to(device)
t1, t2

Device : cuda


(tensor([[0.1249, 0.2243, 0.8818],
         [0.2896, 0.0343, 0.2301]], device='cuda:0'),
 tensor([[0.8655, 0.0829, 0.7657],
         [0.7015, 0.0255, 0.4623]], device='cuda:0'))

### 7.Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors)

In [91]:
import torch 
t1 = torch.rand(2,3)
t2 = torch.rand(2,3)
T = t2.t()
mat = torch.matmul(t1, T)
print(mat)

tensor([[1.1495, 0.8882],
        [0.7950, 0.3683]])


### 8.Find the maximum and minimum values of the output of 7.

In [95]:
import torch
min = torch.min(mat)
max = torch.max(mat)
min, max

(tensor(0.3683), tensor(1.1495))

### 9. Find the maximum and minimum index values of the output of 7.

In [96]:
import torch
argmax = torch.argmax(mat)
argmin = torch.argmin(mat)
argmax, argmin

(tensor(0), tensor(3))

### 10.Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [99]:
import torch
torch.manual_seed(7)
g = torch.rand(size=(1,1,1,10))
d = g.squeeze()
print(g, g.size)
print(d, d.size)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) <built-in method size of Tensor object at 0x0000025C9FBF7430>
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) <built-in method size of Tensor object at 0x0000025C9FBF7AC0>
